from error import Error
class LargoExcedidoError(Error):
    pass